title: Hoya012's Research Blog
description: Study Blog with paper reviews.

#url: http://brianmaierjr.github.com/long-haul
url: https://hoya012.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
#gems: [jekyll-paginate]
gems:
 - jekyll-paginate
 - jekyll-archives
 - jekyll-time-to-read
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Archives
   #url: /archives
   url: /contact

social:
   github: hoya012
   #twitter: brianmaierjr
   facebook: 2.hoseong
   email: hoseong.lee@cognex.com

google_analytics: "UA-58263416-1"
