title: SeongHoon's Study Blog
description: Study Blog

#url: http://brianmaierjr.github.com/long-haul
url: https://u2vvbmdob29uugfyaw.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
#gems: [jekyll-paginate]
gems:
 - jekyll-paginate
 - jekyll-archives
 - jekyll-time-to-read
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: About
   #url: /about
 - title: Archives
   #url: /archives

social:
   #github: brianmaierjr
   #twitter: brianmaierjr
   #facebook: brianmaierjr
   #email:

google_analytics: "UA-58263416-1"
